# -*- coding: utf-8 -*-
"""Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3_0zSq_jTmePryvPMksZO92wt1i-OA8
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("Iris.csv")

X = df.drop("Species", axis=1)
y = df["Species"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion matrix
print(confusion_matrix(y_test, y_pred))

# Naive Bayes is a supervised machine learning classification algorithm based on Bayes Theorem. It is used to classify data into different categories using probability. In this experiment, the Iris dataset is used to classify flowers into Iris-setosa, Iris-versicolor, and Iris-virginica species based on flower measurements.

# The dataset contains numerical features such as sepal length, sepal width, petal length, and petal width. These features act as independent variables (X), while the Species column acts as the target variable (y). The dataset is divided into training and testing data using train_test_split(). The GaussianNB() model from sklearn.naive_bayes is used because the dataset contains continuous numerical values.

# The fit() function trains the Naive Bayes classifier using training data, and the predict() function predicts flower species for testing data. The model performance is evaluated using accuracy score and confusion matrix. Naive Bayes is simple, fast, and widely used in applications such as spam filtering, sentiment analysis, and document classification.