# -*- coding: utf-8 -*-
"""Data Wrangling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZdoWvERrRAMS0MAHw-b-ckT5TPxHgIY
"""

import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/insaid2018/Term-3/master/Data/CaseStudy/titanic_train.csv'
df = pd.read_csv(url)

df.info()

df.describe()

df.shape

df.isnull().sum()

import matplotlib.pyplot as plt
plt.boxplot(df['Age'].dropna())
plt.show()

df["Age"] = df['Age'].fillna(df['Age'].median())

df = df.drop('Cabin', axis = 1)

df["Embarked"] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df.isnull().sum()

df.dtypes

from re import L
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

df.dtypes

df['Fare'] = (df['Fare'] - df['Fare'].min())/ (df['Fare'].max() - df['Fare'].min())

df['Fare']

df.duplicated().sum()

df = df.drop_duplicates()

df['Sex'].unique()

df['Sex'].value_counts()