# -*- coding: utf-8 -*-
"""Data vis 1-2-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrkpcTT5WSo9wXeMrimkDlDP6vcZ3dtZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("titanic.csv")

plt.hist(df["Fare"])

plt.title("Distribution of Fare")

plt.xlabel("Fare")

plt.ylabel("Frequency")
plt.show()

sns.boxplot(x="Sex", y="Age", hue="Survived", data=df)

plt.title("Age Distribution by Gender and Survival")

plt.show()

df = pd.read_csv("Iris.csv")

print(df.dtypes)

df.iloc[:,1:5].hist(figsize=(8,8))

plt.show()

df.iloc[:,1:5].plot(kind='box')

plt.show()

# Data Visualization is the graphical representation of data using charts and plots. It helps in understanding the distribution, spread, patterns, and relationships present in the dataset. Visualization makes data analysis easier and improves interpretation of complex information.

# In this experiment, the Iris dataset is used for visualization and analysis. The dataset contains numerical features such as SepalLengthCm, SepalWidthCm, PetalLengthCm, and PetalWidthCm, along with the categorical feature Species. The dtypes attribute is used to identify the datatype of each feature and classify them as numeric or nominal.

# Histograms are used to visualize the distribution of each numerical feature in the dataset. They show how values are spread across different intervals and help identify skewness or concentration of values. Boxplots are used to visualize the spread of data, median, quartiles, and outliers. Outliers are represented by points outside the whiskers of the boxplot.

# The Id column is excluded from visualization because it acts only as an identifier and does not contribute meaningful analytical information. By comparing histograms and boxplots, it becomes easier to understand feature distributions and detect the presence of outliers in the dataset.

# Data visualization is widely used in data science, machine learning, statistics, and business analytics for better understanding of datasets and effective decision making.