# -*- coding: utf-8 -*-
"""logical and confusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIFXfrXDI75NhuRnGfbeFc9YAhnK4eEJ
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix, accuracy_score

df = pd.read_csv("Social_Network_Ads.csv")

df.head()

X = df[["Age", "EstimatedSalary"]]
y = df["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)

cm = confusion_matrix(y_test, y_pred)

print(cm)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Error rate
print("Error Rate:", 1 - accuracy_score(y_test, y_pred))

# Precision
print("Precision:", precision_score(y_test, y_pred))

# Recall
print("Recall:", recall_score(y_test, y_pred))

# Logistic Regression is a supervised machine learning algorithm used for classification problems. It is used when the output variable is categorical in nature, such as Yes/No, True/False, or 0/1. Unlike Linear Regression, which predicts continuous numerical values, Logistic Regression predicts the probability of occurrence of a class or event. It is widely used in applications like spam detection, disease prediction, customer churn prediction, and purchase prediction.

# In this experiment, the Social Network Ads dataset is used to predict whether a user will purchase a product based on features such as Age and Estimated Salary. These input variables are treated as independent variables (X), while the Purchased column acts as the dependent or target variable (y). The dataset is divided into training data and testing data using the train_test_split() function. Training data is used to train the model, while testing data is used to evaluate model performance on unseen data.

# The LogisticRegression() model from sklearn.linear_model is used to create the classification model. The fit() function trains the model using training data, and the predict() function predicts class labels for testing data. The output of Logistic Regression is generally categorical values such as 0 and 1, representing different classes.

# To evaluate the performance of the classification model, a confusion matrix is used. The confusion matrix contains True Positive (TP), True Negative (TN), False Positive (FP), and False Negative (FN) values. These values help calculate important evaluation metrics such as accuracy, precision, recall, and error rate. Accuracy measures the percentage of correct predictions, precision measures correctness of predicted positive values, recall measures how many actual positive cases were identified correctly, and error rate measures the percentage of incorrect predictions made by the model.

# Logistic Regression is simple, efficient, and widely used for binary classification problems. It is one of the most fundamental algorithms in machine learning and forms the basis for understanding many advanced classification techniques.