# -*- coding: utf-8 -*-
"""Statiscal groupby

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0aInc5Blx01Rg3lfrmhb9VA2ivXdbJz
"""

import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv")

df.describe()

df['Age'].std()

df.groupby('Sex')['Age'].mean()

df = pd.read_csv("Iris.csv")

df.info()

df['Species'].unique()

df.groupby("Species").agg(["mean", "median", "std", "min", "max"])