# -*- coding: utf-8 -*-
"""Train and Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HySh7FrAYswnDUPGB9Gjuul7Qh3LvX4
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

df = pd.read_csv('HousingData.csv')

df.info()

df.isnull().sum()

import matplotlib.pyplot as plt
plt.boxplot(df['CRIM'].dropna())
plt.show()

df['CRIM'] = df['CRIM'].fillna(df['CRIM'].median())

import matplotlib.pyplot as plt
plt.boxplot(df['INDUS'].dropna())
plt.show()

df['INDUS'] = df['INDUS'].fillna(df['INDUS'].mean())

import matplotlib.pyplot as plt
plt.boxplot(df['CHAS'].dropna())
plt.show()

df['CHAS'] = df['CHAS'].fillna(df['CHAS'].median())

import matplotlib.pyplot as plt
plt.boxplot(df['AGE'].dropna())
plt.show()

df['AGE'] = df['AGE'].fillna(df['AGE'].mean())

import matplotlib.pyplot as plt
plt.boxplot(df['LSTAT'].dropna())
plt.show()

df['LSTAT'] = df['LSTAT'].fillna(df['LSTAT'].median())

import matplotlib.pyplot as plt
plt.boxplot(df['ZN'].dropna())
plt.show()

df['ZN'] = df['ZN'].fillna(df['ZN'].median())

df.isnull().sum()

X = df.drop('MEDV', axis= 1)
y = df['MEDV']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

print(comparison.head())

# Linear Regression is a supervised machine learning algorithm used to predict continuous numerical values based on the relationship between input and output variables. It establishes a linear relationship between dependent and independent variables using a best-fit straight line. The main objective of linear regression is to predict the value of a target variable such as house price, salary, marks, or temperature using known input features.

# In this experiment, the Boston Housing dataset is used to predict house prices. The dataset contains various features such as crime rate, number of rooms, tax rate, and other housing-related parameters. These features act as independent variables (X), while the house price (MEDV) acts as the dependent or target variable (y). The model learns the relationship between these variables during training.

# The dataset is divided into training data and testing data using the train_test_split() function. Training data is used to train the model, while testing data is used to evaluate the model performance on unseen data. Generally, 80% data is used for training and 20% for testing. This helps in checking whether the model has learned properly or simply memorized the data.

# The LinearRegression() model from sklearn.linear_model is used to create the regression model. The fit() function trains the model using the training dataset, and the predict() function predicts house prices for the testing dataset. The predicted values are then compared with actual values to evaluate model accuracy and performance.

# Linear Regression is widely used in real-world applications such as house price prediction, sales forecasting, stock market analysis, weather forecasting, and business analytics. It is simple, efficient, and easy to interpret, making it one of the most commonly used machine learning algorithms.